// Generated by Nuxt
// Declare your own types here if needed

declare module '#imports' {
  import type { Ref } from 'vue'
  import type { RouteLocationNormalized } from 'vue-router'

  // Nuxt composables
  export const useHead: typeof import('@nuxt/head')['useHead']
  export const useNuxtApp: typeof import('nuxt/app')['useNuxtApp']
  export const useState: typeof import('nuxt/app')['useState']
  export const computed: typeof import('vue')['computed']
  export const defineNuxtRouteMiddleware: typeof import('nuxt/app')['defineNuxtRouteMiddleware']
  export const withDefaults: typeof import('vue')['withDefaults']
  export const defineProps: typeof import('vue')['defineProps']
  export const defineSlots: typeof import('vue')['defineSlots']
}

declare module '#vue-router' {
  export * from 'vue-router'
}

// Extend process env
declare namespace NodeJS {
  interface ProcessEnv {
    NODE_ENV: 'development' | 'production' | 'test'
  }
} 